### PR TITLE
Set active link navbar

### PR DESCRIPTION
**Pull request by opentechexpert**
Add function to check active link on navbar component.

### CODE REVIEW

**Review by opentechexpert — COMMENTED** [review]
Update menuitem.

**Comment by opentechexpert** [comment]
Looks like vercel did not redeploy updates after update menuitem array.

**Comment by opentechexpert** [comment]
It's working on dev but not in build time.

**Comment by opentechexpert** [comment]
I'll close the pull request. It will not work because script is not running in browser.
Have try different approach.

**Comment by surjithctly** [comment]
this should happen in build time, so try `astro build` as see if it works there.

**Pull request closed without merging**
